#!/bin/bash -e
#
# proxpaas-admin-cli - command-line interface for Proxpaas administration

###########
## UTILS ##
###########

PROXPAAS_BASE_URL=${PROXPAAS_HOST:-http://localhost:4567}/apps

usage() {
    echo "Usage: $(basename $0) [-h] [-s <string>]"
    echo ""
    echo "  -h  Help. Display this message and quit."
    echo "  -c  Setup an app (expect PROXPAAS_APP_ID to be set) based on an IP address."
    echo ""
    exit 1
}

setup_app() {
  if [ -z "$PROXPAAS_APP_ID" ]; then
    echo "PROXPAAS_APP_ID is not set."
    exit 1
  else
    curl -sS -F "ip=$PROXPAAS_APP_IP" $PROXPAAS_BASE_URL/$PROXPAAS_APP_ID/setup > /dev/null
  fi
}

##########
## MAIN ##
##########

if [[ $# -eq 0 ]] ; then
  usage
fi

while getopts "hs:" optchar
do
    case "${optchar}" in
        h)
            usage
            ;;
        s)
            PROXPAAS_APP_IP=$OPTARG
            ;;
        *)
            usage
            ;;
    esac
done

if [ ! -z "$PROXPAAS_APP_IP" ]; then
  setup_app
fi
